
```{r}
library(tidyverse)
load("../results/sim1.rdata")
temp <- group_by(param, nid, overlap, f, xy, ux, uy) %>% summarise()
temp$sim <- 1:nrow(temp)
param <- inner_join(param, temp) %>% as.tibble
```

There is a relationship between simulated f stats and intended f stats

```{r}
out <- group_by(param, sim) %>%
summarise(f=mean(f), fval11=mean(fval11), fval22=mean(fval22), fvalo=mean(fvalo)) %>% select(-sim) %>% as.matrix %>% log
pairs(out)
```

The relationship between effect estimates

```{r}

out <- param %>% group_by(sim) %>%
summarise(
	xy=mean(xy),
	obs11=mean(obs11_beta),
	obs22=mean(obs22_beta),
	obso=mean(obso_beta),
	mr11=mean(mr11_beta),
	mr22=mean(mr22_beta),
	mr12=mean(mr12_beta),
	mr21=mean(mr21_beta),
	mro=mean(mro_beta)
) %>% select(-sim) %>% as.matrix
pairs(out)

out <- filter(param, f > 10) %>% group_by(sim) %>%
summarise(
	xy=mean(xy),
	obs11=mean(obs11_beta),
	obs22=mean(obs22_beta),
	obso=mean(obso_beta),
	mr11=mean(mr11_beta),
	mr22=mean(mr22_beta),
	mr12=mean(mr12_beta),
	mr21=mean(mr21_beta),
	mro=mean(mro_beta)
) %>% select(-sim) %>% as.matrix
pairs(out)

out <- filter(param, fval11 > 10) %>% group_by(sim) %>%
summarise(
	xy=mean(xy),
	obs11=mean(obs11_beta),
	obs22=mean(obs22_beta),
	obso=mean(obso_beta),
	mr11=mean(mr11_beta),
	mr22=mean(mr22_beta),
	mr12=mean(mr12_beta),
	mr21=mean(mr21_beta),
	mro=mean(mro_beta)
) %>% select(-sim) %>% as.matrix
pairs(out[,c(1,2,5,9)])

```

Bias? What proportion of estimates have 95% confidence intervals outside the simulated causal effect?

```{r}
param$obs11_lci <- param$obs11_beta - param$obs11_se * 1.96
param$obs11_uci <- param$obs11_beta + param$obs11_se * 1.96
param$obs22_lci <- param$obs22_beta - param$obs22_se * 1.96
param$obs22_uci <- param$obs22_beta + param$obs22_se * 1.96
param$obso_lci <- param$obso_beta - param$obso_se * 1.96
param$obso_uci <- param$obso_beta + param$obso_se * 1.96
param$mr11_lci <- param$mr11_beta - param$mr11_se * 1.96
param$mr11_uci <- param$mr11_beta + param$mr11_se * 1.96
param$mr22_lci <- param$mr22_beta - param$mr22_se * 1.96
param$mr22_uci <- param$mr22_beta + param$mr22_se * 1.96
param$mr12_lci <- param$mr12_beta - param$mr12_se * 1.96
param$mr12_uci <- param$mr12_beta + param$mr12_se * 1.96
param$mr21_lci <- param$mr21_beta - param$mr21_se * 1.96
param$mr21_uci <- param$mr21_beta + param$mr21_se * 1.96
param$mro_lci <- param$mro_beta - param$mro_se * 1.96
param$mro_uci <- param$mro_beta + param$mro_se * 1.96

out1 <- filter(param) %>% group_by(nid, overlap, f, xy, ux, uy, sim) %>%
summarise(
	obs11=mean(obs11_beta),
	obs22=mean(obs22_beta),
	# obso=mean(obso_beta),
	mr11=mean(mr11_beta),
	mr22=mean(mr22_beta),
	mr12=mean(mr12_beta),
	mr21=mean(mr21_beta),
	mro=mean(mro_beta)
)
out2 <- filter(param) %>% group_by(nid, overlap, f, xy, ux, uy, sim) %>%
summarise(
	obs11=1-sum(obs11_lci < xy & xy < obs11_uci)/n(),
	obs22=1-sum(obs22_lci < xy & xy < obs22_uci)/n(),
	# obso=1-sum(obso_lci < xy & xy < obso_uci)/n(),
	mr11=1-sum(mr11_lci < xy & xy < mr11_uci)/n(),
	mr22=1-sum(mr22_lci < xy & xy < mr22_uci)/n(),
	mr12=1-sum(mr12_lci < xy & xy < mr12_uci)/n(),
	mr21=1-sum(mr21_lci < xy & xy < mr21_uci)/n(),
	mro=1-sum(mro_lci < xy & xy < mro_uci)/n(),
)
out3 <- filter(param, xy == 0) %>% group_by(nid, overlap, f, xy, ux, uy, sim) %>%
summarise(
	obs11=sum(obs11_pval < 0.05)/n(),
	obs22=sum(obs22_pval < 0.05)/n(),
	# obso1-pval(ob0.05)/n(),
	mr11=sum(mr11_pval < 0.05)/n(),
	mr22=sum(mr22_pval < 0.05)/n(),
	mr12=sum(mr12_pval < 0.05)/n(),
	mr21=sum(mr21_pval < 0.05)/n(),
	mro=sum(mro_pval < 0.05)/n(),
)
out4 <- filter(param, xy != 0) %>% group_by(nid, overlap, f, xy, ux, uy, sim) %>%
summarise(
	obs11=sum(obs11_pval < 0.05)/n(),
	obs22=sum(obs22_pval < 0.05)/n(),
	# obso1-pval(ob0.05)/n(),
	mr11=sum(mr11_pval < 0.05)/n(),
	mr22=sum(mr22_pval < 0.05)/n(),
	mr12=sum(mr12_pval < 0.05)/n(),
	mr21=sum(mr21_pval < 0.05)/n(),
	mro=sum(mro_pval < 0.05)/n(),
)
out1l <- gather(out1, key="key", value="value", -c(nid, overlap, f, xy, ux, uy, sim))
out2l <- gather(out2, key="key", value="value", -c(nid, overlap, f, xy, ux, uy, sim))
out3l <- gather(out3, key="key", value="value", -c(nid, overlap, f, xy, ux, uy, sim))
out4l <- gather(out4, key="key", value="value", -c(nid, overlap, f, xy, ux, uy, sim))

ggplot(out2l, aes(x=key, y=value)) +
geom_boxplot()

ggplot(out1l %>% filter(f>10), aes(x=key, y=value-xy)) +
geom_boxplot() +
ylim(-0.5,0.5)

ggplot(out3l, aes(x=key, y=value)) +
geom_boxplot()

ggplot(out4l, aes(x=key, y=value)) +
geom_boxplot()

filter(out1l, key=="mro") %>% ggplot(aes(x=overlap, y=value)) + geom_point(aes(colour=f <11)) + ylim(-1,1) + geom_smooth(method="lm",aes(colour=f<11))
filter(out2l, key=="mr11") %>% ggplot(aes(x=as.factor(overlap), y=value)) + geom_violin()
filter(out3l, key=="mr11") %>% ggplot(aes(x=as.factor(overlap), y=value)) + geom_violin()
filter(out4l, key=="mr11") %>% ggplot(aes(x=as.factor(overlap), y=value)) + geom_violin()

```


```{r}
temp <- filter(param, ux != 0 & uy != 0) %>% group_by(f, overlap) %>%
summarise(r=cor(mro_beta, obs11_beta))

ggplot(temp, aes(x=overlap, y=r, group=as.factor(f))) + geom_point(aes(colour=f)) +
geom_line(aes(colour=f))

temp <- filter(param, ux != 0 & uy != 0 & xy > 0.4) %>% group_by(f, overlap) %>% select(mro_beta, obs11_beta)

ggplot(temp %>% filter(f >= 8), aes(x=obs11_beta, y=mro_beta)) +
# geom_point() +
geom_smooth(method="lm") +
facet_wrap(~ f + overlap, scale="free")

temp <- filter(param, ux != 0 & uy != 0 & xy > 0.4) %>% group_by(f, overlap) %>% select(mro_beta, obs11_beta)

ggplot(temp %>% filter(f >= 8), aes(x=obs11_beta, y=mro_beta)) +
# geom_point() +
geom_smooth(method="lm") +
facet_wrap(~ f + overlap, scale="free")

temp <- filter(param, ux != 0 & uy != 0 & xy > 0.3) %>% group_by(f, ux, uy, overlap) %>% summarise(r=cor(mro_beta, obs11_beta), n=n())

temp %>% ggplot(aes(x=as.numeric(overlap), y=r, group=as.factor(f))) +
geom_point(aes(colour=f)) +
geom_smooth(method="lm")

summary(lm(r ~ overlap * f, temp))

```

